--[[
	Plugin: Spotlights
	Purpose: Keybind defaults for the Spotlights plugin.
	Last updated: 2026-05-15
]]

local Keybinds = {
	ToggleSpotlightLeft = Enum.KeyCode.One,
	ToggleSpotlightRight = Enum.KeyCode.Two,
	RotateSpotlightLeftArmUp = Enum.KeyCode.Q,
	RotateSpotlightLeftArmDown = Enum.KeyCode.A,
	RotateSpotlightRightArmUp = Enum.KeyCode.R,
	RotateSpotlightRightArmDown = Enum.KeyCode.F,
	RotateSpotlightLeftLamp = Enum.KeyCode.E,
	RotateSpotlightRightLamp = Enum.KeyCode.T,
	RotateSpotlightLeftBase = Enum.KeyCode.S,
	RotateSpotlightLeftBaseCounter = Enum.KeyCode.D,
	RotateSpotlightRightBase = Enum.KeyCode.G,
	RotateSpotlightRightBaseCounter = Enum.KeyCode.H,
}

return Keybinds
