--[[
	Plugin: Windows
	Purpose: Keybind defaults for the Windows plugin.
	Last updated: 2026-05-15
]]

local Keybinds = {
	ToggleWindowFL = Enum.KeyCode.Five,
	ToggleWindowFR = Enum.KeyCode.Six,
	ToggleWindowRL = Enum.KeyCode.Seven,
	ToggleWindowRR = Enum.KeyCode.Eight,
	ToggleWindowsAll = Enum.KeyCode.Comma,

	KeybindMap = {
		ToggleWindowFL = "WindowFL",
		ToggleWindowFR = "WindowFR",
		ToggleWindowRL = "WindowRL",
		ToggleWindowRR = "WindowRR",
	},
}

return Keybinds
